spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rascal_db
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update # 운영시에는 validate 추천
    show-sql: true
  messages:
    basename: i18n/exception
    encoding: UTF-8
  jwt:
  secret: rascal!@!^
