spring:
  #profiles: develop
  datasource:
    url: postgres://xcnkbgjjekuerv:49ffc378045924547bf582c3279ac55385262f543b86f454795cdc6b6a810945@ec2-52-3-130-181.compute-1.amazonaws.com:5432/d4dj5c6k9idck9
    username: xcnkbgjjekuerv
    password: 49ffc378045924547bf582c3279ac55385262f543b86f454795cdc6b6a810945
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update # 운영시에는 validate 추천
    generate-ddl: true
    show-sql: true
  jwt:
    secret: rascal!@!^