spring:
  profiles: local-real
  datasource:
    url: jdbc:mysql://localhost:3306/rascal_db
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update # 운영시에는 validate 추천
    show-sql: true
  jwt:
    secret: rascal!@!^

---

spring:
  profiles:
    active: default
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  jwt:
    secret: rascal!@!^